name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: what did you do? What happened exactly?
      placeholder: When I ..., The VSCode button doesn''t show up ... 
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-do-you-expect
    attributes:
      label: What did you expect?
      description: what did you expect exactly?
      placeholder: The VSCode button should be shown ...
      value: "A bug happened!"
    validations:
      required: true
  - type: checkboxes
    id: is-latest
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - label: latest
  - type: input
    id: version
    attributes: 
       label: Which version (if not the latest)?
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
